openapi: 3.0.0
info:
  title: Market Prediction Agent API
  description: AI-powered market prediction system with agentic capabilities
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: http://localhost:3000/api
    description: Development server

paths:
  /health:
    get:
      summary: Health check
      description: Returns API health status
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
                  timestamp:
                    type: string
                    format: date-time
                  uptime:
                    type: number
                    example: 1234.56

  /predict:
    post:
      summary: Generate market prediction
      description: Uses AI agents to analyze market data and generate predictions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - symbol
              properties:
                symbol:
                  type: string
                  description: Stock symbol to analyze
                  example: AAPL
                strategy:
                  type: string
                  enum: [comprehensive, technical, sentiment, momentum]
                  default: comprehensive
                timePreference:
                  type: object
                  properties:
                    macro:
                      type: string
                      example: 2_weeks
                    micro:
                      type: string
                      example: 3_days
                riskTolerance:
                  type: string
                  enum: [low, medium, high]
                  default: medium

      responses:
        '200':
          description: Prediction generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  symbol:
                    type: string
                    example: AAPL
                  prediction:
                    type: object
                    properties:
                      macroTrend:
                        type: object
                        properties:
                          direction:
                            type: string
                            enum: [bullish, bearish, neutral, consolidation]
                          confidence:
                            type: number
                            minimum: 0
                            maximum: 1
                          timeframe:
                            type: string
                          rationale:
                            type: string
                      microTrend:
                        type: object
                        properties:
                          direction:
                            type: string
                            enum: [bullish, bearish, neutral, consolidation_bullish, consolidation_bearish]
                          confidence:
                            type: number
                            minimum: 0
                            maximum: 1
                          timeframe:
                            type: string
                          expectedAction:
                            type: string
                  agentMetadata:
                    type: object
                    properties:
                      analysisStrategy:
                        type: string
                      toolsUsed:
                        type: array
                        items:
                          type: string
                      dataSourcesAnalyzed:
                        type: array
                        items:
                          type: string
                      reasoningSteps:
                        type: number
                      totalAnalysisTime:
                        type: string

        '400':
          description: Invalid request parameters
        '500':
          description: Internal server error

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
        success:
          type: boolean
          example: false
